---
# tasks file for kubeadm-join-masters
- name: reset kubeadm
  shell: kubeadm reset -f
- name: Generated token - 1.
  local_action: shell sed -n 73,75p ./token > ./mastertoken
- name: Copy master token
  copy:
    src: mastertoken
    dest: /tmp/join-command.sh
    owner: root
    group: root
    mode: '0777'
- name: Generated token - 2.
  shell: sed -i 's/\b:80\b/& --apiserver-advertise-address "{{hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']}}" /' /tmp/join-command.sh
- name: Add new Kubernetes master member
  command: sh /tmp/join-command.sh
