---
# tasks file for prerequisites
- name: Upgrade all packages
  yum: name=* state=latest
- name: Install Docker
  package:
    name: docker
    state: latest
  become: yes
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
- name: Disable SELinux
  selinux:
    state: disabled
- name: Reboot the machine
  reboot:
- name: Copy /etc/yum.repos.d/kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'
- name: Upgrade all packages
  yum: name=* state=latest
- name: Install Kubernetes Package
  yum:
    name: "{{packages}}"
    state: present
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
- name: Enable / Start kubelet Service
  service:
    name: kubelet
    state: started
    enabled: yes
- name: Letting iptables see bridged traffic
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
- name: Reload sysctl config for iptables
  command: sysctl --system
- name: Disable SWAP
  command: swapoff -a
- name: Disabling Swap memory permanently
  replace:
   path: /etc/fstab
   regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
   replace: '# \1'
- name: Disable firewalld 
  service:
    name: firewalld
    state: stopped
    enabled : no
